Vagrant.configure('2') do |config|
	config.vm.box = "archlinux_x86_64"
	config.vm.box_url = "http://cloud.terry.im/vagrant/archlinux-x86_64.box"

        config.tun.enabled = true

        config.vm.provision "shell", inline: "pacman -Rsc virtualbox-guest-dkms --noconfirm"
        config.vm.provision "shell", inline: "pacman -Syyu --noconfirm"
end

